biddr_api/biddr_api/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "auctions#index"


  resources :users, only: [:new, :create]

  resource :sessions, only: [:new, :destroy, :create]

  resources :auctions do 
    resources :bids, only: [:create, :destroy]
  end

  
end

biddr_api/biddr_api/app/models/ability.rb
class Ability
    include CanCan::Ability

    def initialize(user)

    user ||= User.new #guest user (not logged in)

    if user.present?
        can :create, :update, :destroy, :all
    else
        can :read, :all
    end

    alias_action :create, :read, :update, :delete, :to => :crud

    can :crud, Auction do |auction|
        user == auction.user
    end
  
    can :crud, Bid do |bid|
        user == bid.user 
    end
    

  end
end

biddr_api/biddr_api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

biddr_api/biddr_api/app/models/auction.rb
class Auction < ApplicationRecord
    has_many :bids, dependent: :destroy
    belongs_to :user, optional: true

    validates :body, presence: true

    def is_valid?
        title.present? &&body.present?
    end
end

biddr_api/biddr_api/app/models/bid.rb
class Bid < ApplicationRecord
    belongs_to :auction
    belongs_to :user, optional: true
    validates :ammount, presence: true
end

biddr_api/biddr_api/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :auctions, dependent: :destroy
    has_many :bids, dependent: :destroy
end

biddr_api/biddr_api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def user_signed_in?
        current_user.present?
    end
        helper_method :user_signed_in?

        helper_method :current_user
      
    private

    def authenticate_user!
        redirect_to new_sessions_path, alert: "Please sign in" unless user_signed_in?
    end

    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end
end

biddr_api/biddr_api/app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :find_auction, only: [:show, :edit, :update, :destroy]
    before_action :authorize_user!, only:[:edit, :update, :destroy]

    def index
        @auctions = Auction.order(created_at: :desc)
        @bid = Bid.new
    end

    def new
        @auction = Auction.new
    end

    def create
        @auction = Auction.new(auction_params)
        @auction.user = current_user
        if @auction.is_valid?
            if @auction.save 
                flash[:success] = "auction successfully created"
                redirect_to @auction
            else
                flash[:error] = "Something went wrong"
                render 'new'
            end
        else
        flash[:alert] = "Please Add Title and Body"
            redirect_to new_auction_path(@auction)
        end
    end

    def show
        @bid = Bid.new
    
    end

    private

    def auction_params
        params.require(:auction).permit(:title, :body, :reserve_price, :end_date)
    end
    def find_auction
        @auction = Auction.find params[:id]
    end

    def authorize_user!
        redirect_to root_path, alert: "Not authorized!" unless can?(:crud, @auction)
    end  

end

biddr_api/biddr_api/app/controllers/bids_controller.rb
class BidsController < ApplicationController
    before_action :authenticate_user!, except: [:show, :index]
    before_action :find_auction

    def create
        @bid = Bid.new(bid_params)
        @bid.auction = @auction
        @bid.user = current_user
        if @bid.save
            flash[:success] = "Bid successfully created"
            redirect_to auction_path(@auction)
        else
            flash[:alert] = "Please Add Text"
            redirect_to auction_path(@auction)
        end
    end

    private
    def find_auction
        @auction = Auction.find params[:auction_id]
    end
    
    def bid_params
        params.require(:bid).permit(:ammount)
    end
end

biddr_api/biddr_api/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      @user = User.find_by_email params[:email]
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Logged in"
      else
        flash[:alert] = "Wrong email or password"
        render :new
      end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!"
    end
end

biddr_api/biddr_api/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
        
    def create
        @user = User.new user_params
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Logged In!"
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :password,
        :password_confirmation
        )
    end

end

biddr_api/biddr_api/app/helpers/application_helper.rb
module ApplicationHelper
end

biddr_api/biddr_api/app/helpers/auctions_helper.rb
module AuctionsHelper
end

biddr_api/biddr_api/app/helpers/bids_helper.rb
module BidsHelper
end

biddr_api/biddr_api/app/helpers/session_helper.rb
module SessionHelper
end

biddr_api/biddr_api/app/helpers/users_helper.rb
module UsersHelper
end

biddr_api/biddr_api/app/views/auctions/_form.html.erb
<%= form_for @auction do |f| %>
  <div>
    <%= f.label :title %>
    <br>
    <%= f.text_field :title, size: 50 %>
  </div>
  <div>
    <%= f.label :body %>
    <br>
    <%= f.text_area :body, :size=>"50" %>
  </div>
  <div>
   <%= f.label :end_date %>
    <br>
    <%= f.datetime_local_field :end_date, :size=>"50" %>
  </div>
  <div>
    <%= f.label :reserve_price %>
    <br>
    <%= f.number_field :reserve_price, :size=>"50" %>
  </div>
  <br>
  <%= f.submit %>
<% end %>

biddr_api/biddr_api/app/views/auctions/_navBar.html.erb
    <nav class="navbar navbar-expand-med navbar-light bg-light">
    <a class="navbar-brand" href="./" style ="margin-left: 5px">
    <img src="https://cdn-icons-png.flaticon.com/512/2570/2570192.png" width="50" height="50" class="d-inline-block align-top" alt="" style ="margin-left: 25px">
     <p>Biddr
     </p>
    </a>
    <p> <% flash.each do |type, message| %>
                <div class="alert alert-info" role=alert >
                <%= type + "--" + message %>
                </div>
            <% end %> <p>

  <div class=" navbar navbar-expand ">
    <ul class="navbar-nav mr-auto">
        <div class=" navbar navbar-expand ">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/auctions" style="color: black ;">Home</a>
                 </li>
                 <li class="nav-item active">
                    <a class="nav-link" href="/auctions/new" style="color: black ;">New Auction</a>
                </li>
                <%if user_signed_in? %>
                    <span class="navbar-text" style ="margin-right: 5px">
                    Hello <%=current_user.first_name %> 
                    </span>
                    <span class="navbar-text" >
                    <%= button_to "Logout", sessions_path, method: :delete,
                    data: {confirm: "are you sure you want to log out?"}%>
                    </span>
                <% else %>
                    <li class="navbar-text">
                       <%=button_to "Login", new_sessions_path, method: :get %>
                    </li>
                    <li class="navbar-text" style ="margin-left: 5px">
                        <%= button_to "Sign Up", new_user_path, method: :get  %>
                    </li>
                <% end %>
  </div>
</nav>

biddr_api/biddr_api/app/views/auctions/index.html.erb
<%= render "navBar" %>

<div class="card-columns" >
  <% @auctions.each do |auction| %>
    <div class="card" style="background-color: #ffffe6">
      <div class="card-body">
        <h5 class="card-title"><%= link_to auction.title, auction%></h5>
        <p class="card-text"><%= auction.body %></p>
        <p class="card-text">
        Created By: <%= auction.user.first_name %> </p>

        </p>
      </div>    
    </div>  
  <% end %>
</div>

biddr_api/biddr_api/app/views/auctions/new.html.erb
<%= render "navBar" %>
<%= render "form" %>

biddr_api/biddr_api/app/views/auctions/show.html.erb
<%= render "navBar" %>

<div class="container">
  <div class="row">
    <div class="col-md">
      <h1><%= @auction.title %></h1>

      <p><%= @auction.body %></p>

      
      <%= @bid.errors.full_messages.join(', ') %>

      <% if user_signed_in? %>
      Place a Bid:
        <%= form_for [@auction, @bid] do |f| %>
            <%= f.number_field :ammount %>

            <%= f.submit %>
        <% end %>
      <% end %>
      <br>

      <h5 style="text-decoration-line: underline;"> Previous Bids </h5>
      <% @auction.bids.each do |bid| %>
          $ <%= bid.ammount %>
          Created <%= time_ago_in_words(bid.created_at) %> ago 
          <hr>
      <% end %>
    </div>
    <div class="col-md">
       <p>
       Current Price: $<%= @auction.bids.maximum(:ammount) %>
       <br>
       Bidding Ends At: <%= @auction.end_date %>
       <br>
        <%# if (@auction.bids.maximum(:ammount) >= @auction.reserve_price) %>
        Reserve Price Met
        <%# else %>
        Reserve Price Not Met
       <%# end %> 
       </p>
    </div>
  </div>
</div>
  

biddr_api/biddr_api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BiddrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

biddr_api/biddr_api/app/views/users/new.html.erb
<%= render "auctions/navBar" %>
<h1>Sign Up</h1>

<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit %>
<% end %>